//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int IdComentario { get; set; }
        public int IdUsuario { get; set; }
        public string Descripcion { get; set; }
        public int IdPublicacion { get; set; }
        public System.DateTime Fecha_Comentario { get; set; }
        public string Activo { get; set; }
        public int MeGusta { get; set; }
    
        public virtual Publicaciones Publicaciones { get; set; }
    }
}
