// <auto-generated />
namespace Libreria_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Agrear_Campos_Adicionales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agrear_Campos_Adicionales));
        
        string IMigrationMetadata.Id
        {
            get { return "201810080620272_Agrear_Campos_Adicionales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
